.TH "ACQ32_WAIT_DEF" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACQ32_WAIT_DEF \- 
.SH SYNOPSIS
.br
.PP
\fC#include <acq32ioctl.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBevent_mask\fP"
.br
.ti -1c
.RI "unsigned \fBtimeout\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned \fBACQ32_WAIT_DEF::event_mask\fP"
.PP
.SS "unsigned \fBACQ32_WAIT_DEF::timeout\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
