.TH "ACQ32_PULL_OUTPUT_DATA_RECORD" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACQ32_PULL_OUTPUT_DATA_RECORD \- 
.SH SYNOPSIS
.br
.PP
\fC#include <acq32busprot.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBsrc_pci\fP"
.br
.ti -1c
.RI "unsigned \fBfunc\fP"
.br
.ti -1c
.RI "unsigned \fBstart\fP"
.br
.ti -1c
.RI "unsigned \fBnsamples\fP"
.br
.ti -1c
.RI "unsigned \fBdata\fP [1]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned \fBACQ32_PULL_OUTPUT_DATA_RECORD::data\fP[1]"
.PP
.SS "unsigned \fBACQ32_PULL_OUTPUT_DATA_RECORD::func\fP"
.PP
.SS "unsigned \fBACQ32_PULL_OUTPUT_DATA_RECORD::nsamples\fP"
.PP
.SS "unsigned \fBACQ32_PULL_OUTPUT_DATA_RECORD::src_pci\fP"
.PP
.SS "unsigned \fBACQ32_PULL_OUTPUT_DATA_RECORD::start\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
