.TH "ACQ32_RW_DEF" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACQ32_RW_DEF \- 
.SH SYNOPSIS
.br
.PP
\fC#include <acq32ioctl.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBoffset\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   __u16 \fBw\fP"
.br
.ti -1c
.RI "   __u32 \fBl\fP"
.br
.ti -1c
.RI "} \fBdata\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "union { ... } 
         \fBACQ32_RW_DEF::data\fP"
.PP
.SS "__u32 \fBACQ32_RW_DEF::l\fP"
.PP
.SS "unsigned \fBACQ32_RW_DEF::offset\fP"
.PP
.SS "__u16 \fBACQ32_RW_DEF::w\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
