.TH "Card" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Card \- 
.SH SYNOPSIS
.br
.PP
\fC#include <llcontrol.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBslot\fP"
.br
.RI "\fIdefine resources dedicated to each card \fP"
.ti -1c
.RI "\fBMU\fP * \fBmbx\fP"
.br
.ti -1c
.RI "\fBDmaBuffer\fP * \fBbuf\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBDmaBuffer\fP* \fBCard::buf\fP"
.PP
.SS "struct \fBMU\fP* \fBCard::mbx\fP"
.PP
.SS "int \fBCard::slot\fP"
.PP
define resources dedicated to each card 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
