.TH "DefinitionFileHandler" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DefinitionFileHandler \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDefinitionFileHandler\fP (const char *_def_file)"
.br
.ti -1c
.RI "int \fBgetMaxLines\fP (void)"
.br
.ti -1c
.RI "void \fBprocessFile\fP (\fBInputLineHandler\fP< T > *handler)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "int \fBisComment\fP (const char *my_line)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "const char * \fBdef_file\fP"
.br
.in -1c

.SS "template<class T> class DefinitionFileHandler< T >"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class T> \fBDefinitionFileHandler\fP< T >::\fBDefinitionFileHandler\fP (const char * _def_file)\fC [inline]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "template<class T> int \fBDefinitionFileHandler\fP< T >::getMaxLines (void)\fC [inline]\fP"
.PP
.SS "template<class T> int \fBDefinitionFileHandler\fP< T >::isComment (const char * my_line)\fC [inline, protected]\fP"
.PP
.SS "template<class T> void \fBDefinitionFileHandler\fP< T >::processFile (\fBInputLineHandler\fP< T > * handler)\fC [inline]\fP"
.PP
.SH "Field Documentation"
.PP 
.SS "template<class T> const char* \fBDefinitionFileHandler\fP< T >::\fBdef_file\fP\fC [protected]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
