.TH "DmaBuffer" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DmaBuffer \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBu32\fP * \fBvaddr\fP"
.br
.ti -1c
.RI "int \fBnbytes\fP"
.br
.ti -1c
.RI "\fBSegmentMap\fP \fBseg_map\fP [MAX_SEGMENTS]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBDmaBuffer::nbytes\fP"
.PP
.SS "struct \fBSegmentMap\fP \fBDmaBuffer::seg_map\fP[MAX_SEGMENTS]"
.PP
.SS "\fBu32\fP* \fBDmaBuffer::vaddr\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
