.TH "fetchbs.m" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fetchbs.m \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBwhile\fP (\fBi\fP++< c1-1) fread(fd"
.br
.ti -1c
.RI "\fBchx\fP (:, \fBi\fP)"
.br
.ti -1c
.RI "endfor \fBfclose\fP (fd)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "function \fBchx\fP"
.br
.ti -1c
.RI "\fBi\fP = 0"
.br
.ti -1c
.RI "\fBlen\fP"
.br
.ti -1c
.RI "\fBshort\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "chx (:, \fBi\fP)"
.PP
.SS "endfor fclose (fd)"
.PP
.SS "while ()"
.PP
.SH "Variable Documentation"
.PP 
.SS "chx"
.PP
\fBInitial value:\fP
.PP
.nf
 fetchbs(path, c1, c2, len)
         fd = fopen(path, 'r')
.fi
.SS "endwhile for \fBi\fP = 0"
.PP
.SS "\fBlen\fP"
.PP
.SS "\fBshort\fP"
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
