.TH "InputOffsetHandler" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InputOffsetHandler \- Input Offsets are value,value,value 16 per line.  

.PP
.SH SYNOPSIS
.br
.PP
Inherits \fBInputLineHandler< struct LLC200_INIT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBhandleLine\fP (char myline[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Input Offsets are value,value,value 16 per line. 
.PP
.SH "Member Function Documentation"
.PP 
.SS "virtual void InputOffsetHandler::handleLine (char myline[])\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBInputLineHandler< struct LLC200_INIT >\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
