.TH "MESSAGE_HEADER" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MESSAGE_HEADER \- 
.SH SYNOPSIS
.br
.PP
\fC#include <acq32busprot.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBshort\fP \fBid\fP"
.br
.ti -1c
.RI "unsigned \fBshort\fP \fBlength\fP"
.br
.ti -1c
.RI "unsigned \fBtype\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned \fBshort\fP \fBMESSAGE_HEADER::id\fP"
.PP
.SS "unsigned \fBshort\fP \fBMESSAGE_HEADER::length\fP"
.PP
.SS "unsigned \fBMESSAGE_HEADER::type\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
