.TH "READ_LOCALBUF_DESCR" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
READ_LOCALBUF_DESCR \- 
.SH SYNOPSIS
.br
.PP
\fC#include <acq32ioctl.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBshort\fP * \fBbuffer\fP"
.br
.ti -1c
.RI "int \fBnsamples\fP"
.br
.ti -1c
.RI "int \fBistart\fP"
.br
.ti -1c
.RI "int \fBistride\fP"
.br
.ti -1c
.RI "int \fBflags\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBshort\fP* \fBREAD_LOCALBUF_DESCR::buffer\fP"
.PP
.SS "int \fBREAD_LOCALBUF_DESCR::flags\fP"
.PP
.SS "int \fBREAD_LOCALBUF_DESCR::istart\fP"
.PP
.SS "int \fBREAD_LOCALBUF_DESCR::istride\fP"
.PP
.SS "int \fBREAD_LOCALBUF_DESCR::nsamples\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
