.TH "SegmentMap" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SegmentMap \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBoffset\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "\fBu32\fP \fBphysaddr\fP"
.br
.ti -1c
.RI "int \fBpad\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "int \fBSegmentMap::length\fP"
.PP
.SS "int \fBSegmentMap::offset\fP"
.PP
.SS "int \fBSegmentMap::pad\fP"
.PP
.SS "\fBu32\fP \fBSegmentMap::physaddr\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
