.TH "STATUS_CHANGE_NOTIFICATION_REQUEST" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
STATUS_CHANGE_NOTIFICATION_REQUEST \- 
.SH SYNOPSIS
.br
.PP
\fC#include <acq32busprot.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned \fBrequest_mask\fP"
.br
.ti -1c
.RI "unsigned \fBresponse_mask\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned \fBSTATUS_CHANGE_NOTIFICATION_REQUEST::request_mask\fP"
.PP
.SS "unsigned \fBSTATUS_CHANGE_NOTIFICATION_REQUEST::response_mask\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
