.TH "TextFileReader" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TextFileReader \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextFileReader\fP (const char *\fBfname\fP)"
.br
.ti -1c
.RI "\fB~TextFileReader\fP ()"
.br
.ti -1c
.RI "char * \fBgetLine\fP (char *myline, int maxline)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TextFileReader::TextFileReader (const char * fname)\fC [inline]\fP"
.PP
.SS "TextFileReader::~TextFileReader ()\fC [inline]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "char* TextFileReader::getLine (char * myline, int maxline)\fC [inline]\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
