.TH "ULL_LUT" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ULL_LUT \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBkey\fP"
.br
.ti -1c
.RI "unsigned long long \fBmask\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const char* \fBULL_LUT::key\fP"
.PP
.SS "unsigned long long \fBULL_LUT::mask\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
