.TH "VRangeHandler" 3 "1 Dec 2005" "llcontrol" \" -*- nroff -*-
.ad l
.nh
.SH NAME
VRangeHandler \- 
.SH SYNOPSIS
.br
.PP
Inherits \fBInputLineHandler< struct LLC200_INIT >\fP.
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVRangeHandler\fP (const struct \fBULL_LUT\fP *_lut)"
.br
.ti -1c
.RI "virtual void \fBhandleLine\fP (char myline[])"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VRangeHandler::VRangeHandler (const struct \fBULL_LUT\fP * _lut)\fC [inline]\fP"
.PP
.SH "Member Function Documentation"
.PP 
.SS "virtual void VRangeHandler::handleLine (char myline[])\fC [inline, virtual]\fP"
.PP
Reimplemented from \fBInputLineHandler< struct LLC200_INIT >\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for llcontrol from the source code.
