#!/usr/bin/perl

open CMDLINE, "/proc/cmdline" or die "failed to open /proc/cmdline";

@args = split( / /, <CMDLINE> );

close CMDLINE;

$key=$ARGV[0];
$print_keyvalue_pair = $ARGV[1] eq "print_keyvalue_pair";

foreach $arg (@args) {
	if ( $key eq "" ){
		print "$arg\n";
	}elsif ( $print_keyvalue_pair ){
		if ( $arg =~ /^$key/ ){
			print "$arg ";
		}
	}elsif ( ( $value ) = $arg =~ /$key=(\w+)/ ){
		print $value;
	}
}


	


