# Makefile for Apps


all install release clean:
	(cd HTSTREAM; make $@)
	(cd LOWLATENCY; make $@)
	(cd BIGDUMPTEST; make $@)
	(cd CAL;make $@)
	(cd DUMP; make $@)
	(cd FMU; make $@)
	(cd MISC-TEST; make $@)
