#!/bin/bash

BOARD=${BOARD:-1}
VERBOSE=${VERBOSE:-0}

loadall() {
	for t in 0 1 2 3 4 5 6 7
	do
		for c in 00 01 02 03 04 05 06 07 08 09 \
	                 10 11 12 13 14 15 16 17 18 19 \
	                 20 21 22 23 24 25 26 27 28 29 \
		         30 31 32
		do
			if [ "$VERBOSE" != "0" ]; then
				echo "chan id /dev/wav232/$BOARD/$t/$c";
			fi
			odev=/dev/wav232/$BOARD/$t/$c
			dd if=/dev/zero bs=1024000 count=1 of=$odev 2>/dev/null
		done
	done
}

time loadall

