/*****************************************************************************
 *
 * File:
 *
 * Created by IntelliJ IDEA.
 * User: pgm
 * Date: May 27, 2002
 * Time: 12:35:59 PM
 *
 * $RCSfile: DigitalTriggerFrame.java,v $
 *
 * Copyright (C) 2002 D-TACQ Solutions Ltd
 * not to be used without owner's permission
 *
 * Description:
 *
 * $Id: DigitalTriggerFrame.java,v 1.4.4.1 2004/06/01 14:35:04 pgm Exp $
 * $Log: DigitalTriggerFrame.java,v $
 * Revision 1.4.4.1  2004/06/01 14:35:04  pgm
 * abandoned dt100gui package expt
 *
 * Revision 1.4  2002/06/12 20:25:24  pgm
 * no control without commit, ChannelMask is per board
 *
 * Revision 1.3  2002/05/27 10:25:10  pgm
 * std headers throughout
 *
 *
 *
\*****************************************************************************/
import java.awt.*;
import javax.swing.*;

public class DigitalTriggerFrame extends FrameWithModel
{
	public DigitalTriggerFrame()
	{
		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		getContentPane().setLayout(new BorderLayout(0,0));
		setSize(405,305);
		setVisible(false);
		dtrigPanel.setLayout(new GridBagLayout());
		getContentPane().add(BorderLayout.CENTER, dtrigPanel);
		dtrigPanel.setBounds(0,0,405,305);
		JTextArea1.setText("WORKTODO\nConfigure any DI line to any function\nCPCI routing\n");
		dtrigPanel.add(JTextArea1, new com.symantec.itools.awt.GridBagConstraintsD(0,0,1,1,0.0,0.0,java.awt.GridBagConstraints.CENTER,java.awt.GridBagConstraints.BOTH,new Insets(0,0,0,0),0,0));
		JTextArea1.setBounds(105,122,195,60);
		//}}

		//{{INIT_MENUS
		//}}
	}

	public DigitalTriggerFrame(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b)
	{
		if (b)
			setLocation(50, 50);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new DigitalTriggerFrame()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets and menu bar
		Insets insets = getInsets();
		javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
		int menuBarHeight = 0;
		if (menuBar != null)
			menuBarHeight = menuBar.getPreferredSize().height;
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	javax.swing.JPanel dtrigPanel = new javax.swing.JPanel();
	javax.swing.JTextArea JTextArea1 = new javax.swing.JTextArea();
	//}}

	//{{DECLARE_MENUS
	//}}
    public void initModel() {
            ;
    }

}