/*****************************************************************************
 *
 * File:
 *
 * Created by IntelliJ IDEA.
 * User: pgm
 * Date: May 27, 2002
 * Time: 12:35:59 PM
 *
 * $RCSfile: SignalConditioningFrame.java,v $
 *
 * Copyright (C) 2002 D-TACQ Solutions Ltd
 * not to be used without owner's permission
 *
 * Description:
 *
 * $Id: SignalConditioningFrame.java,v 1.4 2002/05/27 10:25:10 pgm Exp $
 * $Log: SignalConditioningFrame.java,v $
 * Revision 1.4  2002/05/27 10:25:10  pgm
 * std headers throughout
 *
 *
 *
\*****************************************************************************/

import java.awt.*;
import javax.swing.*;

import dt100.*;

public class SignalConditioningFrame extends FrameWithModel
{
	public SignalConditioningFrame()
	{
	    // pgm WORKTODO .. can't get VCafe to recognise these components,
	    // so zap orig object (wasteful, but that's what the GC is for :-)
	    signalConditioningDioSetupTable = new RowSelectTable();
	    signalConditioningChannelSetupTable = new ColumnSelectTable();

		// This code is automatically generated by Visual Cafe when you add
		// components to the visual environment. It instantiates and initializes
		// the components. To modify the code, only use code syntax that matches
		// what Visual Cafe can generate, or Visual Cafe may be unable to back
		// parse your Java file into its visual environment.
		//{{INIT_CONTROLS
		setTitle("Signal Conditioning SC1 setup");
		getContentPane().setLayout(new GridBagLayout());
		getContentPane().setBackground(java.awt.Color.white);
		setSize(405,305);
		setVisible(false);
		signalconditioningPanel.setToolTipText("configure SC1 signal conditioning modules, if attached");
		signalconditioningPanel.setLayout(new GridBagLayout());
		signalconditioningPanel.setEnabled(false);
		getContentPane().add(signalconditioningPanel, new com.symantec.itools.awt.GridBagConstraintsD(0,0,1,1,1.0,1.0,java.awt.GridBagConstraints.CENTER,java.awt.GridBagConstraints.BOTH,new Insets(0,0,0,0),0,0));
		signalconditioningPanel.setBounds(0,0,405,305);
		JPanel18.setLayout(new GridBagLayout());
		signalconditioningPanel.add(JPanel18, new com.symantec.itools.awt.GridBagConstraintsD(0,0,1,1,1.0,0.0,java.awt.GridBagConstraints.NORTHWEST,java.awt.GridBagConstraints.HORIZONTAL,new Insets(0,0,0,0),0,0));
		JPanel18.setBackground(java.awt.Color.lightGray);
		JPanel18.setBounds(0,0,405,97);
		JLabel18.setText("Digital IO :");
		JPanel18.add(JLabel18, new com.symantec.itools.awt.GridBagConstraintsD(0,0,1,1,0.0,0.0,java.awt.GridBagConstraints.NORTHWEST,java.awt.GridBagConstraints.NONE,new Insets(10,10,0,10),0,0));
		JLabel18.setBounds(10,10,56,15);
		JScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
		JScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
		JScrollPane3.setAutoscrolls(true);
		JScrollPane3.setOpaque(true);
		JPanel18.add(JScrollPane3, new com.symantec.itools.awt.GridBagConstraintsD(0,1,1,1,1.0,0.0,java.awt.GridBagConstraints.CENTER,java.awt.GridBagConstraints.HORIZONTAL,new Insets(8,8,8,8),300,30));
		JScrollPane3.setBounds(8,33,389,56);
		signalConditioningDioSetupTable.setRowHeight(24);
		signalConditioningDioSetupTable.setToolTipText("<click> to edit, <SHIFT><click> to act on a range");
		signalConditioningDioSetupTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		signalConditioningDioSetupTable.setAutoscrolls(false);
		JScrollPane3.getViewport().add(signalConditioningDioSetupTable);
		signalConditioningDioSetupTable.setFont(new Font("Dialog", Font.PLAIN, 24));
		signalConditioningDioSetupTable.setBounds(0,0,0,0);
		JPanel20.setLayout(new GridBagLayout());
		signalconditioningPanel.add(JPanel20, new com.symantec.itools.awt.GridBagConstraintsD(0,1,1,1,1.0,1.0,java.awt.GridBagConstraints.NORTHWEST,java.awt.GridBagConstraints.BOTH,new Insets(0,0,0,0),0,0));
		JPanel20.setBackground(java.awt.Color.lightGray);
		JPanel20.setBounds(0,97,405,208);
		JLabel19.setText("Channel Setup");
		JLabel19.setAutoscrolls(true);
		JPanel20.add(JLabel19, new com.symantec.itools.awt.GridBagConstraintsD(0,0,1,1,1.0,0.0,java.awt.GridBagConstraints.NORTH,java.awt.GridBagConstraints.NONE,new Insets(7,7,7,0),0,0));
		JLabel19.setBounds(165,7,82,15);
		JScrollPane4.setOpaque(true);
		JPanel20.add(JScrollPane4, new com.symantec.itools.awt.GridBagConstraintsD(0,1,1,1,1.0,1.0,java.awt.GridBagConstraints.CENTER,java.awt.GridBagConstraints.BOTH,new Insets(0,0,0,0),300,100));
		JScrollPane4.setBounds(0,29,405,179);
		signalConditioningChannelSetupTable.setToolTipText("<click> to edit, <SHIFT><click> to act on a column range");
		JScrollPane4.getViewport().add(signalConditioningChannelSetupTable);
		signalConditioningChannelSetupTable.setBounds(0,0,402,0);
		//}}

		//{{INIT_MENUS
		//}}

		//{{REGISTER_LISTENERS
		SymAction lSymAction = new SymAction();
		//}}
	}

	public SignalConditioningFrame(String sTitle)
	{
		this();
		setTitle(sTitle);
	}

	public void setVisible(boolean b)
	{
		if (b)
			setLocation(50, 50);
		super.setVisible(b);
	}

	static public void main(String args[])
	{
		(new SignalConditioningFrame()).setVisible(true);
	}

	public void addNotify()
	{
		// Record the size of the window prior to calling parents addNotify.
		Dimension size = getSize();

		super.addNotify();

		if (frameSizeAdjusted)
			return;
		frameSizeAdjusted = true;

		// Adjust size of frame according to the insets and menu bar
		Insets insets = getInsets();
		javax.swing.JMenuBar menuBar = getRootPane().getJMenuBar();
		int menuBarHeight = 0;
		if (menuBar != null)
			menuBarHeight = menuBar.getPreferredSize().height;
		setSize(insets.left + insets.right + size.width, insets.top + insets.bottom + size.height + menuBarHeight);
	}

	// Used by addNotify
	boolean frameSizeAdjusted = false;

	//{{DECLARE_CONTROLS
	javax.swing.JPanel signalconditioningPanel = new javax.swing.JPanel();
	javax.swing.JPanel JPanel18 = new javax.swing.JPanel();
	javax.swing.JLabel JLabel18 = new javax.swing.JLabel();
	javax.swing.JScrollPane JScrollPane3 = new javax.swing.JScrollPane();
	javax.swing.JTable signalConditioningDioSetupTable = new javax.swing.JTable();
	javax.swing.JPanel JPanel20 = new javax.swing.JPanel();
	javax.swing.JLabel JLabel19 = new javax.swing.JLabel();
	javax.swing.JScrollPane JScrollPane4 = new javax.swing.JScrollPane();
	javax.swing.JTable signalConditioningChannelSetupTable = new javax.swing.JTable();
	//}}

	//{{DECLARE_MENUS
	//}}


	class SymAction implements java.awt.event.ActionListener
	{
		public void actionPerformed(java.awt.event.ActionEvent event)
		{
		}
	}

    Dt100 dt100 = Dt100.instance();
    public static SC_DioTableModel     theSC_DioTableModel = new SC_DioTableModel();
    public static SC_ChannelTableModel theSC_ChannelTableModel = new SC_ChannelTableModel();

   protected void onCommit() {
        System.out.println( "SignalConditioningFrame.onCommit() STUB" );

		// to do: code goes here.
		// set DIO

		dt100.setDIO( theSC_DioTableModel.toString() );

		// set channels

		for ( int ichannel = 0; ichannel != 32; ++ichannel ){
		    SC_ChannelDef cd = theSC_ChannelTableModel.channels[ichannel];

		    dt100.setChannel(  cd.getChannel(), cd.getG1(), cd.getG2(), cd.getV_EX() );
		}
	}
    public void initModel() {
        theSC_DioTableModel.setTable( signalConditioningDioSetupTable );
        theSC_ChannelTableModel.setTable( signalConditioningChannelSetupTable );
    }

}